pom.xml
Added che jar resource to build. Jekyll build now uses source in target directory.
=> Added che jar resource to build. 

pom.xml
Use Che docs jar with sources classifier for build
=> Use classifier for che sources

src/main/_docs/index.html, src/main/_includes/header.html, src/main/_layouts/default.html, src/main/_sass/_gridism.scss, src/main/_sass/_style.scss
Change styles for the index.html page
Signed-off-by: Stevan Le Meur <stevan.lemeur@gmail.com>
=> Change styles for the index.html page

src/main/_docs/integration-guide/integration-continuous-integration.md
Added info for BitBucket into the CI docs
=> Added bitbucket config info

pom.xml, src/main/_config.yml, src/main/_data/docs.yml, src/main/_data/tutorials.yml, src/main/_plugins/links.rb, src/main/assembly/build_war.yml, src/main/docs.sh
Set new license year
https://github.com/codenvy/infrastructure/issues/40
=> Set new license year

pom.xml
use dependency version from props
=> use dependency version from props

src/main/_docs/admin-guide/admin-managing.md
Added short documentation on how to generate an audit log and provided a sample.
=> Added audit docs

src/main/_docs/integration-guide/integration-version-control.md
Cleaning up the formatting so it displays better in Jekyll.
=> Cleanup for version control section

src/main/_docs/admin-guide/admin-installation.md
Minor tweaks to clarify the proxy section in response to customer feedback.
=> minor proxy language tweaks

src/main/_docs/admin-guide/admin-installation.md
4 customer have run into No healthy swarm node in the cluster.
=> Add port 23750 to the list of must have opened ports on AIO

src/main/_docs/integration-guide/integration-continuous-integration.md, src/main/_docs/integration-guide/integration-issue-management.md
- Updates according to integration properties.
- Removed connctors and webhooks instructions from JIRA item because it is not necessary to configure webhooks and connectors for JIRA.
=> CODENVY-1597: integration config update

src/main/_docs/admin-guide/admin-cli.md
Documentation for https://github.com/eclipse/che/issues/3886
Change-Id: I45c6d3a3b2844a34990b06945e5c84abbee45e4c
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>
=> che#3886 : add graceful stop command

src/main/_docs/admin-guide/admin-cli.md, src/main/_docs/admin-guide/admin-installation.md
- Add updated CLI info to head of CLI page
- Updated install page
Signed-off-by: Brad Micklea <bmicklea@codenvy.com>
=> CLI update

src/main/_docs/admin-guide/admin-configuration.md
Clarified oAuth based on feedback from two users.
=> oAuth clarification

src/main/_docs/admin-guide/admin-installation.md
Signed-off-by: Brad Micklea <bmicklea@codenvy.com>
=> fix offline syntax

src/main/_docs/admin-guide/admin-configuration.md
Just once sentence but it'll help configure Gmail in one step.
=> Configure gmail as smtp

src/main/_docs/admin-guide/admin-installation.md, src/main/_docs/admin-guide/admin-managing.md
Solves this issue.
https://github.com/codenvy/codenvy/issues/1779#event-962979360
=> Add info on ws nodes being public IP address

src/main/_docs/admin-guide/admin-installation.md
Related to https://github.com/codenvy/codenvy/pull/1771
=> Add WS DNS to setup-configuration.md

src/main/_docs/admin-guide/admin-configuration.md
Related to https://github.com/codenvy/codenvy/pull/1791
=> Added LinkIn oAuth to admin-configuration.md

src/main/_docs/admin-guide/admin-configuration.md, src/main/_docs/admin-guide/admin-managing.md
Add missed information about configuration for account resources limits
Add instructions for admin to override account resources limits
https://github.com/codenvy/codenvy/pull/1789
=> Add information about account resources limits

src/main/_docs/integration-guide/integration-workspace-automation.md
Fixing https://github.com/codenvy/codenvy/issues/1911
=> Fix wrong URL format for URL Factories

.gitignore, src/main/_layouts/docs.html
- Fix che improve this page links
- Update .gitignore so that factory will not bring che images and docs over.
=> Fix improve links

src/main/_docs/admin-guide/admin-configuration.md
Adds description about email subjects customization.
=> ENTERPRiSE-67: Email subjects customization

src/main/_docs/admin-guide/admin-installation.md
A few sentences that make things clearer
=> Small additions to proxy docs

src/main/_docs/getting-started.md
Fixes links in the bottom of the intro page.
Signed-off-by: Brad Micklea <bmicklea@codenvy.com>
=> update links in intro page

.factory.json, README.md
This factory file is specific to codenvy.io . Running Codenvy onprem you will need to change 'eth1' to 'eth0'. Someone from Codenvy will need to merge this.
=> Add factory file

pom.xml
=> set actual parent

LICENSE, pom.xml, src/main/_config.yml, src/main/_data/docs.yml, src/main/_data/env.yml, src/main/_data/links.yml, src/main/_data/tutorials.yml, src/main/_plugins/links.rb, src/main/docs.sh
Change license to EPL. "Set Red Hat, Inc." as contributor
https://github.com/codenvy/codenvy/issues/2323
=> Change license to EPL

src/main/_docs/admin-guide/admin-cli.md, src/main/_docs/admin-guide/admin-installation.md, src/main/_docs/admin-guide/admin-managing.md, src/main/_docs/white-labels/labels-introduction-white-labels.md
https://github.com/codenvy/codenvy/issues/2350
=> CODENVY-2350: Remove system license
